### ISSUE TITLE
[Feat] log4back

### ISSUE THREAD

**Issue by kkyu0718** [cmc-say/cmc-server#108]
## 📌  Feature Description
log 관리 
## 📝  To-do
- [ ] log4back 적용
- [ ] dev, prod, 공통 환경 분리
- [ ] 로컬 환경에서 build하고 테스트해보기
