### ISSUE TITLE
[Fix] 해시태그 추가 삭제 url 수정 및 http 메소드 수정

### ISSUE THREAD

**Issue by kkyu0718** [cmc-say/cmc-server#123]
## 🦾  Fix Description
해시태그 추가 삭제 url 수정 및 http 메소드 수정
## 📝  To-do
- [x] 해시태그 추가 url 수정
- [x] 해시태그 삭제 url 수정
- [x] 해시태그 삭제 메소드 post로 변경
