### ISSUE TITLE
[Feat] application.yml gitignore 및 배포시 생성 코드 작성

### ISSUE THREAD

**Issue by kkyu0718** [cmc-say/cmc-server#53]
## 📌  Feature Description
application.yml 은 보안 유지 이슈 때문에 환경 변수를 이용하여 작성되어 있었으나 그대로 배포 파일에 들어가버리면 환경 변수를 따로 설정해야하는 문제가 생겼습니다.
환경 변수를 넣어주는 것 조차도 github workflows에 적고 secrets에 넣어줘야하는 번거로움이 있어 아예 application.yml 전체를 넣어주는 방식으로 변경합니다.
## 📝  To-do
- [x] application.dev.yml 작성
- [x] application.test.yml 작성
- [x] application.dev.yml, application.test.yml jasypt, application.prod.yml 적용
- [ ] github secret으로 jasypt-password 넣어주는 코드 작성 (ec2 was 작동 잘하는지 확인)
