### ISSUE TITLE
[Feat] todo, avatar_todo 도메인 api 

### ISSUE THREAD

**Issue by kkyu0718** [cmc-say/cmc-server#66]
## 📌  Feature Description
todo 엔티티 관련 api 개발
## 📝  To-do
- [x] todo 엔티티 작성
- [x] avatar_todo 엔티티 작성
- [x] avatar_todo 를 아바타에 양방향 매핑
- [x] avatar_todo 를 todo 에 양방향 매핑
- [x] 세계관 저장 api 에 todo 엔티티 저장 추가
- [x] 세계관 캐릭터 전체의 체크리스트 달성 현황 조회 GET /world/{worldId}/board
