### ISSUE TITLE
[Feat] 아바타 crud api

### ISSUE THREAD

**Issue by kkyu0718** [cmc-say/cmc-server#71]
## 📌  Feature Description
아바타 crud 
## 📝  To-do
- [x] 캐릭터 사진 수정
- [x] 캐릭터 정보 수정
- [x] 캐릭터 정보 조회
- [x] 캐릭터 삭제
